import Foundation

/// Non-visual configuration: endpoints, paths, polling intervals and identifiers.
enum Constants {
    static let appName = "NotchNull"
    static let bundleIdentifier = "dev.notchnull.app"

    enum Agents {
        static let eventServerPort: UInt16 = 47_823
        static let claudeUsageURL = URL(string: "https://api.anthropic.com/api/oauth/usage")!
        static let claudeOAuthBeta = "oauth-2025-04-20"
        static let claudeKeychainService = "Claude Code-credentials"
        static let claudeUsageInterval: TimeInterval = 90
        static let codexPollInterval: TimeInterval = 2
        static let codexActiveWindow: TimeInterval = 15 * 60
        static let tokenStatsInterval: TimeInterval = 120
        static let doneLingerSeconds: TimeInterval = 6
        static let sessionForgetAfter: TimeInterval = 3 * 60 * 60
        static let hookEvents = [
            "SessionStart", "UserPromptSubmit", "PermissionRequest", "Notification",
            "PostToolUse", "Stop", "SessionEnd",
        ]
        static let hookMarker = "notchnull-hook"
    }

    enum Paths {
        static let home = FileManager.default.homeDirectoryForCurrentUser
        static let claudeSettings = home.appendingPathComponent(".claude/settings.json")
        static let claudeProjects = home.appendingPathComponent(".claude/projects")
        static let codexSessions = home.appendingPathComponent(".codex/sessions")
        static let downloads = home.appendingPathComponent("Downloads")

        static var support: URL {
            let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            let dir = base.appendingPathComponent(appName, isDirectory: true)
            try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            return dir
        }

        static var tray: URL { support.appendingPathComponent("Tray", isDirectory: true) }
        static var trayIndex: URL { support.appendingPathComponent("tray.json") }
        static var clipboardStore: URL { support.appendingPathComponent("clipboard.sealed") }
        static var clipboardKey: URL { support.appendingPathComponent("clipboard.key") }
        static var hookScript: URL { support.appendingPathComponent("claude-hook.sh") }
        static var hookToken: URL { support.appendingPathComponent("hook-token") }
    }

    enum Intervals {
        static let clipboardPoll: TimeInterval = 0.5
        static let mediaPoll: TimeInterval = 1
        static let statsSample: TimeInterval = 2
        static let downloadPoll: TimeInterval = 0.5
        static let calendarRefresh: TimeInterval = 60
        static let brightnessPoll: TimeInterval = 0.15
        /// Faster polling right after a change, so held brightness keys track without lag.
        static let brightnessActivePoll: TimeInterval = 0.04
        static let batteryEnergySample: TimeInterval = 10
        static let powerModePoll: TimeInterval = 20
    }

    enum Durations {
        static let hud: TimeInterval = 1.5
        static let charging: TimeInterval = 3.2
        static let accessory: TimeInterval = 4
        /// Devices reported this soon after launch were already attached, so they are not announced.
        static let deviceLaunchQuiet: TimeInterval = 4
        static let screenshot: TimeInterval = 4.5
        static let downloadDone: TimeInterval = 4
        static let hello: TimeInterval = 3.4
        static let usageWarning: TimeInterval = 5
        static let meetingLead: TimeInterval = 5 * 60
    }

    enum Limits {
        static let clipboardItems = 60
        static let clipboardTextBytes = 200_000
        static let clipboardImageBytes = 6_000_000
        static let trayItems = 40
        static let statsHistory = 40
    }

    enum Clipboard {
        static let ignoredTypes = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
        ]
    }

    enum Meeting {
        static let hosts = [
            "zoom.us", "meet.google.com", "teams.microsoft.com", "teams.live.com",
            "webex.com", "whereby.com", "around.co", "meet.jit.si", "facetime.apple.com",
        ]
    }

    /// Terminal-like apps we can bring forward when an agent needs attention.
    static let terminalBundleIDs: [String: String] = [
        "Apple_Terminal": "com.apple.Terminal",
        "iTerm.app": "com.googlecode.iterm2",
        "ghostty": "com.mitchellh.ghostty",
        "WezTerm": "com.github.wez.wezterm",
        "WarpTerminal": "dev.warp.Warp-Stable",
        "vscode": "com.microsoft.VSCode",
        "zed": "dev.zed.Zed",
    ]
}
